### ISSUE TITLE
You also HAVE to assign yourself to this issue.

### ISSUE THREAD

**Issue by hvgazula** [gaiborjosue/trained-models-fork#60]
Can users assign themselves to the issue if they are not members of the repo? If yes, how is it possible?

**Comment by gaiborjosue** [comment]
Hello @hvgazula thank you for pointing out this issue. You are correct. I didn't realize that members outside the repo can't assign themselves to the repo. However, there is no problem. I will update the docs saying they only have to change the label to "Ready-to-test" instead of assigning themselves and the workflow will run just fine :)
